# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rajat Jain
# email: your-email@example.com
description: Choice. The problem is choice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rajattjainn
github_username:  rajattjainnn


header_pages:
  - _pages/guides.md
  - _pages/tech.md
  - _pages/interpersonal.md
  - _pages/creatives.md
  - _pages/cv.md

collections:
  guides:
    output: true
  tech:
    output: true
  interpersonal:
    output: true
  creatives:
    output: true

include:
  - _pages
  - _tech


defaults:
  - scope:
      path: ""
    values:
      image: https://rajattjainn.github.io/assets/img/rajat.png


twitter:
  username: rajattjainn
  card: summary_large_image

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
